name: Goldberg Emulator (CMake Linux)

on:
  workflow_dispatch:  # manual trigger

jobs:
  build_cmake_linux:
    runs-on: ubuntu-latest
    container:
      image: ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt update -y
          apt install -y build-essential cmake libprotobuf-dev protobuf-compiler ninja-build

      - name: Configure and build (x64 release)
        run: |
          mkdir cmake-builds && cd cmake-builds
          mkdir x64-release && cd x64-release
          cmake ../../ -G "Ninja" -DCMAKE_BUILD_TYPE:STRING="RelWithDebInfo"
          ninja

      # Optional: Experimental build (uncomment if needed)
      # - name: Configure and build (x64 experimental release)
      #   run: |
      #     mkdir -p cmake-builds/x64-experimental-release && cd cmake-builds/x64-experimental-release
      #     cmake ../../ -G "Ninja" -DCMAKE_BUILD_TYPE:STRING="RelWithDebInfo" -DEMU_EXPERIMENTAL_BUILD:BOOL=ON
      #     ninja

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cmake-builds
          path: cmake-builds/
