name: Goldberg Emulator for SteamOS

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  protobuf_static_steamos:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: protobuf/
          key: protobuf-static-steamos-cache

      - run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y build-essential git autotools-dev automake libtool gcc-multilib g++-multilib libc6-dev-i386

      - run: |
          if [ -e ./protobuf/prefix ]; then
            echo "Protobuf already built, skipping..."
            exit 0
          fi

          export BASE_PREFIX_PATH=$(pwd)
          echo "Base prefix path: $BASE_PREFIX_PATH"

          mkdir -p deps
          cd deps

          git clone --branch 21.x https://github.com/protocolbuffers/protobuf.git
          cd protobuf

          sh autogen.sh
          ./configure 'CC=gcc -m32' 'CXX=g++ -m32' CPPFLAGS='-fPIC -Ofast' CXXFLAGS='-fPIC -Ofast' --prefix=$BASE_PREFIX_PATH/protobuf/prefix_x86/ --disable-shared --enable-static
          make -j$(nproc) install
          make clean

          ./configure 'CC=gcc' 'CXX=g++' CPPFLAGS='-fPIC -Ofast' CXXFLAGS='-fPIC -Ofast' --prefix=$BASE_PREFIX_PATH/protobuf/prefix/ --disable-shared --enable-static
          make -j$(nproc) install

      - uses: actions/upload-artifact@v4
        with:
          name: protobuf
          path: protobuf/

  build_steamos:
    needs: protobuf_static_steamos
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download protobuf artifact
        uses: actions/download-artifact@v4
        with:
          name: protobuf
          path: protobuf

      - name: Build project inside Docker
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt -y install gcc g++ git libtool build-essential \
            libx11-dev libxext-dev libxi-dev libxrandr-dev libxinerama-dev \
            libgl1-mesa-dev libglu1-mesa-dev \
            gcc-multilib g++-multilib libc6-dev-i386 \
            libgl1-mesa-dev:i386 libx11-dev:i386 libxext-dev:i386

          echo 'System Info:'
          uname -a
          ls -lah

          chmod -R 755 ./protobuf

          sed -i 's|../protobuf/prefix|./protobuf/prefix|g' build_steamos.sh

          sh build_steamos.sh

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: linux/
