name: Build Goldberg Emulator for SteamOS (Dockerized)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  protobuf_static_steamos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore protobuf cache
        uses: actions/cache@v3
        with:
          path: protobuf/
          key: protobuf-static-steamos-cache

      - name: Build protobuf static inside Docker
        run: |
          if [ -e ./protobuf/prefix ]; then
            echo "Protobuf already built, skipping..."
            exit 0
          fi

          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace tianon/steamos bash -c "
            apt update && apt -y install gcc-4.9 g++-4.9 git autotools-dev automake libtool g++-4.9-multilib gcc-4.9-multilib build-essential &&

            export BASE_PREFIX_PATH=\$(pwd)
            echo 'Base prefix path: '\$BASE_PREFIX_PATH

            mkdir deps
            cd deps

            git clone --branch 21.x https://github.com/protocolbuffers/protobuf.git
            cd protobuf

            sh autogen.sh
            ./configure 'CC=gcc-4.9 -m32' 'CXX=g++-4.9 -m32' CPPFLAGS='-fPIC -Ofast' CXXFLAGS='-fPIC -Ofast' --prefix=\$BASE_PREFIX_PATH/protobuf/prefix_x86/ --disable-shared --enable-static
            make -j\$(nproc) install
            make clean

            ./configure 'CC=gcc-4.9' 'CXX=g++-4.9' CPPFLAGS='-fPIC -Ofast' CXXFLAGS='-fPIC -Ofast' --prefix=\$BASE_PREFIX_PATH/protobuf/prefix/ --disable-shared --enable-static
            make -j\$(nproc) install
          "

      - name: Upload protobuf artifact
        uses: actions/upload-artifact@v4
        with:
          name: protobuf
          path: protobuf/

  build_steamos:
    needs: protobuf_static_steamos
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download protobuf artifact
        uses: actions/download-artifact@v3
        with:
          name: protobuf
          path: protobuf

      - name: Build project inside Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace tianon/steamos bash -c "
            apt update && apt -y install gcc-4.9 g++-4.9 git libtool g++-4.9-multilib gcc-4.9-multilib &&

            echo 'System Info:'
            uname -a
            ls -lah

            sed -i 's/^g++ /g++-4.9 /g' build_steamos.sh
            sed -i 's|../protobuf/prefix|./protobuf/prefix|g' build_steamos.sh

            sh build_steamos.sh
          "

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: linux/
