name: Build Goldberg Emulator for Windows (Linux + Wine)

on:
  workflow_dispatch:
  push:
    branches:
      - main  # or your target branch

jobs:
  build_windows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y wine64 wget p7zip-full sed dos2unix python3 python3-pip

      - name: Convert line endings
        run: |
          find . -name "*.txt" -exec unix2dos {} +
          find ./files_example -type f -name "*.txt" -exec unix2dos {} +

      - name: Fix protobuf directories in batch file
        run: sed -i 's/..\\vcpkg\\installed\\/.\\protobuf_/g' build_set_protobuf_directories.bat

      - name: Download dependencies
        run: |
          wget 'https://gitlab.com/Mr_Goldberg/goldberg_emulator/uploads/48db8f434a193aae872279dc4f5dde6a/sdk_standalone.7z'
          wget 'https://gitlab.com/Mr_Goldberg/goldberg_emulator/uploads/0119304e030098b4821d73170fe52084/protobuf_x64-windows-static.7z'
          wget 'https://gitlab.com/Mr_Goldberg/goldberg_emulator/uploads/4185a97ab363ddc1859127e59ec68581/protobuf_x86-windows-static.7z'

      - name: Extract archives
        run: |
          7z x protobuf_x86-windows-static.7z -oprotobuf_x86-windows-static
          7z x protobuf_x64-windows-static.7z -oprotobuf_x64-windows-static
          7z x sdk_standalone.7z -osdk_standalone

      - name: Update DLL files in batch scripts
        run: |
          DLL_FILES="$(ls dll/*.cpp | tr "\n" " ")"
          sed -i "s|dll/\*.cpp|$DLL_FILES|g" *.bat

          DLL_FILES="$(ls dll/*.proto | tr "\n" " " | sed 's/\.proto/.pb.cc/g')"
          sed -i "s|dll/\*.cc|$DLL_FILES|g" *.bat

      - name: Update /MP flag in batch scripts
        run: sed -i "s| /MP12 | /MP4 |g" *.bat

      - name: Generate build batch file
        run: python3 generate_build_win_bat.py

      - name: Build with Wine
        env:
          WINEDEBUG: -all
        run: wine cmd /c build_win_release_test.bat

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: release/
