name: Build Goldberg Emulator for Windows (Native)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install 7zip
        run: choco install 7zip -y

      - name: Download dependencies
        run: |
          Invoke-WebRequest -Uri 'https://gitlab.com/Mr_Goldberg/goldberg_emulator/uploads/48db8f434a193aae872279dc4f5dde6a/sdk_standalone.7z' -OutFile 'sdk_standalone.7z'
          Invoke-WebRequest -Uri 'https://gitlab.com/Mr_Goldberg/goldberg_emulator/uploads/0119304e030098b4821d73170fe52084/protobuf_x64-windows-static.7z' -OutFile 'protobuf_x64-windows-static.7z'
          Invoke-WebRequest -Uri 'https://gitlab.com/Mr_Goldberg/goldberg_emulator/uploads/4185a97ab363ddc1859127e59ec68581/protobuf_x86-windows-static.7z' -OutFile 'protobuf_x86-windows-static.7z'

      - name: Extract archives
        run: |
          7z x sdk_standalone.7z -osdk_standalone
          7z x protobuf_x64-windows-static.7z -oprotobuf_x64-windows-static
          7z x protobuf_x86-windows-static.7z -oprotobuf_x86-windows-static

      - name: Convert line endings
        run: |
          Get-ChildItem -Recurse -Include *.txt | ForEach-Object { (Get-Content $_.FullName) | Set-Content $_.FullName }

      #- name: Generate build batch file
      #  run: python generate_build_win_bat.py
      
      - name: Fix protobuf directories in batch file
        run: (Get-Content build_set_protobuf_directories.bat) -replace '..\\vcpkg\\installed\\.', 'protobuf_' | Set-Content build_set_protobuf_directories.bat

      - name: Update DLL files in batch scripts
        run: |
          $dllFiles = Get-ChildItem dll -Filter *.cpp | ForEach-Object { $_.FullName -replace '.*dll\\', 'dll\\' } | Join-String " "
          (Get-Content build_win_release.bat) -replace 'dll/\*.cpp', $dllFiles | Set-Content build_win_release.bat

          $protoFiles = Get-ChildItem dll -Filter *.proto | ForEach-Object { $_.FullName -replace '.*dll\\', 'dll\\' } | ForEach-Object { $_ -replace '\.proto$', '.pb.cc' } | Join-String " "
          (Get-Content build_win_release.bat) -replace 'dll/\*.cc', $protoFiles | Set-Content build_win_release.bat

      - name: Build project
        run: cmd /c build_win_release.bat

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: release/
