name: Build CMake Windows (via Wine)

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build_cmake_windows:
    runs-on: ubuntu-latest
    container:
      image: fedora:29

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          dnf -y install wine wget p7zip sed dos2unix unzip

      - name: Download and extract dependencies
        run: |
          wget 'https://gitlab.com/Mr_Goldberg/goldberg_emulator/uploads/48db8f434a193aae872279dc4f5dde6a/sdk_standalone.7z'
          7za x sdk_standalone.7z -osdk_standalone

          wget 'https://github.com/Kitware/CMake/releases/download/v3.15.0-rc1/cmake-3.15.0-rc1-win64-x64.zip'
          7za x cmake-3.15.0-rc1-win64-x64.zip

          wget 'https://gitlab.com/Mr_Goldberg/goldberg_emulator/uploads/0119304e030098b4821d73170fe52084/protobuf_x64-windows-static.7z'
          7za x protobuf_x64-windows-static.7z -oprotobuf_x64-windows-static

      - name: Build x64 release
        run: |
          export WINEDEBUG=-all
          mkdir -p cmake-builds/x64-release
          cd cmake-builds/x64-release

          echo call .\\..\\..\\sdk_standalone\\set_vars64.bat >> cmake-build.bat
          echo .\\..\\..\\cmake-3.15.0-rc1-win64-x64\\bin\\cmake.exe ..\\.. -G \"NMake Makefiles\" -DCMAKE_BUILD_TYPE:STRING=\"RelWithDebInfo\" -DCMAKE_PREFIX_PATH=\"protobuf_x64-windows-static\" -DProtobuf_PROTOC_EXECUTABLE:STRING=\"./../../protobuf_x64-windows-static/tools/protobuf/protoc.exe\" >> cmake-build.bat
          echo nmake.exe >> cmake-build.bat

          wine cmd /c cmake-build.bat

      - name: Build x64 experimental release
        run: |
          export WINEDEBUG=-all
          mkdir -p cmake-builds/x64-experimental-release
          cd cmake-builds/x64-experimental-release

          echo call .\\..\\..\\sdk_standalone\\set_vars64.bat >> cmake-build.bat
          echo .\\..\\..\\cmake-3.15.0-rc1-win64-x64\\bin\\cmake.exe ..\\.. -G \"NMake Makefiles\" -DCMAKE_BUILD_TYPE:STRING=\"RelWithDebInfo\" -DE
